# OJOK EMMANUEL NSUBUGA 

- Registration number: 21/U/06816/PS
- Student number: 2100706816

### DATA ANALYSIS WITH PANDAS (EXERCISE SET 2)

#### SERIES

Import libraries

In [98]:
# import pandas
import pandas as pd

Question 1

In [99]:
# Create the sample series
series1 = pd.Series([4, 65, 436, 3, 9])
series2 = pd.Series([7, 0, 3, 897, 9])

# Compare the elements of the two series
comparison_result = series1 == series2

# Display the comparison result
print(comparison_result)

0    False
1    False
2    False
3    False
4     True
dtype: bool

Question 2

In [100]:
# Create the sample series
series1 = pd.Series([2, 4, 6, 8, 14])
series2 = pd.Series([1, 3, 5, 7, 9])

# Addition
addition_result = series1 + series2
print("Addition:")
print(addition_result)

# Subtraction
subtraction_result = series1 - series2
print("\nSubtraction:")
print(subtraction_result)

# Multiplication
multiplication_result = series1 * series2
print("\nMultiplication:")
print(multiplication_result)

# Division
division_result = series1 / series2
print("\nDivision:")
print(division_result)

Addition:
0     3
1     7
2    11
3    15
4    23
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    5
dtype: int64

Multiplication:
0      2
1     12
2     30
3     56
4    126
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

Question 3

In [101]:
# Sample dictionary
dictionary1 = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}

# Convert dictionary to series
series1 = pd.Series(dictionary1)

# Display the resulting series
print(series1)

Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

Question 4

In [102]:
# we have to import numpy
import numpy as np

# Sample series
series1 = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])

# Convert series to array
array1 = np.array(series1)

# Display the resulting array
print(array1)

['Love' 800 'Joy' 789.9 'Peace' True]

Question 5

In [103]:
# load the dataset
df = pd.read_csv("AfricaCupofNationsMatches.csv")

In [104]:
# Get the most frequent value
most_frequent_value = df['HomeTeamGoals'].mode().values[0]
print(most_frequent_value)

# Replace everything else as 'Other'
df['HomeTeamGoals'] = df['HomeTeamGoals'].where(df['HomeTeamGoals'] == most_frequent_value, 'Other')

# Display the modified series
print(df['HomeTeamGoals'])

1.0
0        1.0
1      Other
2      Other
3      Other
4        1.0
       ...
617    Other
618      1.0
619    Other
620    Other
621    Other
Name: HomeTeamGoals, Length: 622, dtype: object

#### DATAFRAMES

Question 1

In [105]:
# load the dataset
df = pd.read_csv("AfricaCupofNationsMatches.csv")

Question 2

In [106]:
# Get the first 7 rows
first_7_rows = df.head(7)

# Display the result
first_7_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0

Question 3

In [107]:
# Select the desired columns
selected_columns = df[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]

# Display the selected columns
selected_columns

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

Question 4

In [108]:
# Select the rows where 'Egypt' appears in any column
selected_rows = df[df.applymap(lambda x: 'Egypt' in str(x)).any(axis=1)]

# Display the selected rows
selected_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
7,1962,18-Jan-62,NaN,Egypt,Uganda,2.0,1.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
569,2017,5 February 2017 (2017-02-05),20:00,Egypt,Cameroon,1.0,2.0,Final,NaN,Stade de l'Amitié,Libreville,NaN
570,2019,21 June 2019 (2019-06-21),22:00,Egypt,Zimbabwe,1.0,0.0,Group A,NaN,Cairo International Stadium,Cairo,73299.0
573,2019,26 June 2019 (2019-06-26),22:00,Egypt,DR Congo,2.0,0.0,Group A,NaN,Cairo International Stadium,Cairo,74219.0
574,2019,30 June 2019 (2019-06-30),21:00,Uganda,Egypt,0.0,2.0,Group A,NaN,Cairo International Stadium,Cairo,74566.0
609,2019,6 July 2019 (2019-07-06),21:00,Egypt,South Africa,0.0,1.0,Round of 16,NaN,Cairo International Stadium,Cairo,75000.0

Question 5

In [109]:
# Count the number of rows and columns
num_rows = df.shape[0]
num_columns = df.shape[1]

# Display the counts
print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

Number of rows: 622
Number of columns: 12

Question 6

In [110]:
# Select the rows where 'Attendance' is missing
selected_rows = df[df['Attendance'].isnull()]

# Display the selected rows
selected_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
10,1963,24-Nov-63,NaN,Ghana,Tunisia,1.0,1.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
11,1963,26-Nov-63,NaN,Ghana,Ethiopia,2.0,0.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
565,2017,29 January 2017 (2017-01-29),20:00,Egypt,Morocco,1.0,0.0,Quarter-finals,NaN,Stade de Port-Gentil,Port-Gentil,NaN
566,2017,1 February 2017 (2017-02-01),20:00,Burkina Faso,Egypt,1.0,1.0,Semi-finals,Egypt win on Penalities 3-4,Stade de l'Amitié,Libreville,NaN
567,2017,2 February 2017 (2017-02-02),20:00,Cameroon,Ghana,2.0,0.0,Semi-finals,NaN,Stade de Franceville,Franceville,NaN
568,2017,4 February 2017 (2017-02-04),20:00,Burkina Faso,Ghana,1.0,0.0,Third place play-off,NaN,Stade de Port-Gentil,Port-Gentil,NaN
569,2017,5 February 2017 (2017-02-05),20:00,Egypt,Cameroon,1.0,2.0,Final,NaN,Stade de l'Amitié,Libreville,NaN

Question 7

In [111]:
# Select the rows where 'HomeTeamGoals' are between 3 and 6 (inclusive)
selected_rows = df[(df['HomeTeamGoals'] >= 3) & (df['HomeTeamGoals'] <= 6)]

# Display the selected rows
selected_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
553,2017,20 January 2017 (2017-01-20),20:00,Morocco,Togo,3.0,1.0,Group C,NaN,Stade d'Oyem,Oyem,NaN
585,2019,27 June 2019 (2019-06-27),22:00,Kenya,Tanzania,3.0,2.0,Group C,NaN,30 June Stadium,Cairo,7233.0
595,2019,24 June 2019 (2019-06-24),22:00,Mali,Mauritania,4.0,1.0,Group E,NaN,Suez Stadium,Suez,6202.0
608,2019,6 July 2019 (2019-07-06),18:00,Nigeria,Cameroon,3.0,2.0,Round of 16,NaN,Alexandria Stadium,Alexandria,10000.0
611,2019,7 July 2019 (2019-07-07),21:00,Algeria,Guinea,3.0,0.0,Round of 16,NaN,30 June Stadium,Cairo,8205.0

Question 8

In [112]:
# Change the value of "AwayTeamGoals" in the 3rd row to 10
df.at[2, 'AwayTeamGoals'] = 10

# Display the modified DataFrame
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

Question 9

In [113]:
# Sort the DataFrame by 'HomeTeam' in ascending order, then by 'HomeTeamScores' in descending order
# HomeTeamScores column is not in the dataset so I will use HomeTeamGoals instead
sorted_df = df.sort_values(['HomeTeam', 'HomeTeamGoals'], ascending=[True, False])

# Display the sorted DataFrame
sorted_df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
205,1990,2-Mar-90,NaN,Algeria,Nigeria,5.0,1.0,Group A,NaN,Stade 5 Juillet 1962,Algiers,85000.0
29,1968,14-Jan-68,NaN,Algeria,Uganda,4.0,0.0,Group A,NaN,Hailé Sélassié Stadium,Addis Ababa,25000.0
135,1980,16-Mar-80,NaN,Algeria,Guinea,3.0,2.0,Group B,NaN,Liberty Stadium,Ibadan,20000.0
164,1984,5-Mar-84,NaN,Algeria,Malawi,3.0,0.0,Group B,NaN,Stade Bouaké,Bouaké,10000.0
171,1984,17-Mar-84,NaN,Algeria,Egypt,3.0,1.0,Third place match,NaN,Stade Félix Houphouët-Boigny,Abidjan,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
521,2012,12-Feb-12,20:30[note 1],Zambia,Ivory Coast,0.0,0.0,Final,Zambia win on Penalities 8-7,Stade d'Angondjé,Libreville,40000.0
549,2017,23 January 2017 (2017-01-23),20:00,Zimbabwe,Tunisia,2.0,4.0,Group B,NaN,Stade de l'Amitié,Libreville,NaN
398,2004,25-Jan-04,16:30,Zimbabwe,Egypt,1.0,2.0,Group C,NaN,Stade Taïeb El Mhiri,Sfax,22000.0
437,2006,23-Jan-06,20:00,Zimbabwe,Senegal,0.0,2.0,Group D,NaN,Port Said Stadium,Port Said,15000.0
575,2019,30 June 2019 (2019-06-30),21:00,Zimbabwe,DR Congo,0.0,4.0,Group A,NaN,30 June Stadium,Cairo,4364.0

Question 10

In [114]:
# Get the list of column headers
column_headers = df.columns.tolist()

# Display the list of column headers
column_headers

['Year',
 'Date ',
 'Time ',
 'HomeTeam',
 'AwayTeam',
 'HomeTeamGoals',
 'AwayTeamGoals',
 'Stage',
 'SpecialWinConditions',
 'Stadium',
 'City',
 'Attendance']

Question 11

In [115]:
# Create a new column with the desired data
new_column_data = [10] * len(df)  # Example data to fill the new column
column_name = 'MyRandomColumn'  # Name of the new column

# Append the new column to the DataFrame
df[column_name] = new_column_data

# Display the modified DataFrame
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,MyRandomColumn
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,10
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,10
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,10
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,10
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0,10
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0,10
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,10
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,10
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,10

Question 12

In [116]:
# Create two rows with NaN values
new_rows = [{"Year":2020,"Date":"July-10-2020","Time":"22:00","HomeTeam":"Uganda","AwayTeam":"Senegal",
             "HomeTeamGoals":4,"AwayTeamGoals":1,"Stage":"Final","SpecialWinConditions":np.nan,
             "Stadium":"Stade International du Caire","City":"Cairo","Attendance":40000,"MyRandomColumn":10},
             {"Year":2021,"Date":"June-13-2020","Time":"21:00","HomeTeam":"Senegal","AwayTeam":"Kenya",
             "HomeTeamGoals":3,"AwayTeamGoals":2,"Stage":"Final","SpecialWinConditions":np.nan,
             "Stadium":"Namboole Stadium","City":"Kampala","Attendance":32000,"MyRandomColumn":10}
             ]

# Add the new rows to the DataFrame
for row in new_rows:
    df.loc[len(df)] = row

# Display the modified DataFrame
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,MyRandomColumn
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,10
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,10
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,10
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,10
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,10
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,10
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,10
622,2020,NaN,NaN,Uganda,Senegal,4.0,1.0,Final,NaN,Stade International du Caire,Cairo,40000.0,10
623,2021,NaN,NaN,Senegal,Kenya,3.0,2.0,Final,NaN,Namboole Stadium,Kampala,32000.0,10

Question 13

In [117]:
# Change 'Uganda' to 'China' in the 'AwayTeam' column
df['AwayTeam'] = df['AwayTeam'].replace('Uganda', 'China')

# Display the modified DataFrame
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,MyRandomColumn
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,10
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,10
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,10
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,10
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,10
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,10
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,10
622,2020,NaN,NaN,Uganda,Senegal,4.0,1.0,Final,NaN,Stade International du Caire,Cairo,40000.0,10
623,2021,NaN,NaN,Senegal,Kenya,3.0,2.0,Final,NaN,Namboole Stadium,Kampala,32000.0,10

Question 14

In [118]:
# Reset the index of the DataFrame
df.reset_index(drop=True, inplace=True)

# Display the modified DataFrame
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,MyRandomColumn
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,10
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,10
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,10
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,10
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,10
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,10
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,10
622,2020,NaN,NaN,Uganda,Senegal,4.0,1.0,Final,NaN,Stade International du Caire,Cairo,40000.0,10
623,2021,NaN,NaN,Senegal,Kenya,3.0,2.0,Final,NaN,Namboole Stadium,Kampala,32000.0,10

Question 15

In [119]:
# Check if 'Stadium' column is present in the DataFrame
if 'Stadium' in df.columns:
    print("The 'Stadium' column is present in the DataFrame.")
else:
    print("The 'Stadium' column is not present in the DataFrame.")

The 'Stadium' column is present in the DataFrame.

Question 16

In [120]:
# data types of the columns before
df.dtypes

# Convert the data type of 'AwayTeamGoals' to float
df['AwayTeamGoals'] = df['AwayTeamGoals'].astype(float)

# Display the modified DataFrame
df.dtypes

Year                      int64
Date                     object
Time                     object
HomeTeam                 object
AwayTeam                 object
HomeTeamGoals           float64
AwayTeamGoals           float64
Stage                    object
SpecialWinConditions     object
Stadium                  object
City                     object
Attendance              float64
MyRandomColumn            int64
dtype: object

Question 17

In [121]:
# Remove the last 10 rows from the DataFrame
df = df.iloc[:-10]

# Display the modified DataFrame
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,MyRandomColumn
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,10
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,10
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,10
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,10
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,2019,6 July 2019 (2019-07-06),21:00,Egypt,South Africa,0.0,1.0,Round of 16,NaN,Cairo International Stadium,Cairo,75000.0,10
610,2019,7 July 2019 (2019-07-07),18:00,Madagascar,DR Congo,2.0,2.0,Round of 16,Madagascar win on Penalities 4-2,Alexandria Stadium,Alexandria,5890.0,10
611,2019,7 July 2019 (2019-07-07),21:00,Algeria,Guinea,3.0,0.0,Round of 16,NaN,30 June Stadium,Cairo,8205.0,10
612,2019,8 July 2019 (2019-07-08),18:00,Mali,Ivory Coast,0.0,1.0,Round of 16,NaN,Suez Stadium,Suez,7672.0,10
613,2019,8 July 2019 (2019-07-08),21:00,Ghana,Tunisia,1.0,1.0,Round of 16,Tunisia win on Penalities 4-5,Ismailia Stadium,Ismailia,8890.0,10

Question 18

In [122]:
# Iterate over rows in the DataFrame
for index, row in df.iterrows():
    # Access row data using row[column_name]
    print("Row index:", index)
    print("HomeTeam:", row['HomeTeam'])
    print("AwayTeam:", row['AwayTeam'])
    print("HomeTeamGoals:", row['HomeTeamGoals'])
    print("AwayTeamGoals:", row['AwayTeamGoals'])
    print("-------------------")

Question 19

In [125]:
# Define the desired column order
new_column_order = ['AwayTeam', 'HomeTeam', 'AwayTeamGoals', 'HomeTeamGoals',
                     'Year','Stage','MyRandomColumn', 'SpecialWinConditions',
                       'Stadium', 'City', 'Attendance']

# Reorder the columns based on the new order
df = df[new_column_order]

# Display the modified DataFrame
df

,AwayTeam,HomeTeam,AwayTeamGoals,HomeTeamGoals,Year,Stage,MyRandomColumn,SpecialWinConditions,Stadium,City,Attendance
0,Egypt,Sudan,2.0,1.0,1957,Semifinals,10,NaN,Municipal Stadium,Khartoum,30000.0
1,South Africa,Ethiopia,NaN,NaN,1957,Semifinals,10,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,Ethiopia,Egypt,10.0,4.0,1957,Final,10,NaN,Municipal Stadium,Khartoum,30000.0
3,Ethiopia,Egypt,0.0,4.0,1959,Final Tournament,10,NaN,Prince Farouk Stadium,Cairo,30000.0
4,Ethiopia,Sudan,0.0,1.0,1959,Final Tournament,10,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...
609,South Africa,Egypt,1.0,0.0,2019,Round of 16,10,NaN,Cairo International Stadium,Cairo,75000.0
610,DR Congo,Madagascar,2.0,2.0,2019,Round of 16,10,Madagascar win on Penalities 4-2,Alexandria Stadium,Alexandria,5890.0
611,Guinea,Algeria,0.0,3.0,2019,Round of 16,10,NaN,30 June Stadium,Cairo,8205.0
612,Ivory Coast,Mali,1.0,0.0,2019,Round of 16,10,NaN,Suez Stadium,Suez,7672.0
613,Tunisia,Ghana,1.0,1.0,2019,Round of 16,10,Tunisia win on Penalities 4-5,Ismailia Stadium,Ismailia,8890.0

Question 20

In [127]:
# Filter the DataFrame to keep only rows where 'HomeTeamGoals' is not equal to 0
df = df[df['HomeTeamGoals'] != 0]

# Reset the index of the modified DataFrame
df.reset_index(drop=True, inplace=True)

# Display the modified DataFrame
df

,AwayTeam,HomeTeam,AwayTeamGoals,HomeTeamGoals,Year,Stage,MyRandomColumn,SpecialWinConditions,Stadium,City,Attendance
0,Egypt,Sudan,2.0,1.0,1957,Semifinals,10,NaN,Municipal Stadium,Khartoum,30000.0
1,South Africa,Ethiopia,NaN,NaN,1957,Semifinals,10,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,Ethiopia,Egypt,10.0,4.0,1957,Final,10,NaN,Municipal Stadium,Khartoum,30000.0
3,Ethiopia,Egypt,0.0,4.0,1959,Final Tournament,10,NaN,Prince Farouk Stadium,Cairo,30000.0
4,Ethiopia,Sudan,0.0,1.0,1959,Final Tournament,10,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...
484,Benin,Morocco,1.0,1.0,2019,Round of 16,10,Benin win on Penalities 1-4,Al Salam Stadium,Cairo,7500.0
485,Cameroon,Nigeria,2.0,3.0,2019,Round of 16,10,NaN,Alexandria Stadium,Alexandria,10000.0
486,DR Congo,Madagascar,2.0,2.0,2019,Round of 16,10,Madagascar win on Penalities 4-2,Alexandria Stadium,Alexandria,5890.0
487,Guinea,Algeria,0.0,3.0,2019,Round of 16,10,NaN,30 June Stadium,Cairo,8205.0
488,Tunisia,Ghana,1.0,1.0,2019,Round of 16,10,Tunisia win on Penalities 4-5,Ismailia Stadium,Ismailia,8890.0

End of assignment *Thank you*